# Your Bot's config values

from:
  currency: CLP  # 3 digits currency code
  address: any  # 'any' if fiat or every address
to:
  currency: BTC  # 3 digits currency code
  withdraw: True  # True to withdraw converted amount
  address: '1AViXz9M16snuRfyvKoSKkFWcc7APphyAB'  # leave blank for fiat
